### ISSUE TITLE
download window - inactive downloads not visible

### ISSUE THREAD

**Issue by omega3** [JustOff/advanced-night-mode#10]
Font for inactive downloads in Download window is black and therefore it is not well enough visible.

https://i.imgur.com/u16Ua4o.png

Can this add-on have separate colour setting for Download window, both for background and font, please.

**Comment by JustOff** [comment]
This window is styled by your browser theme, not ANM.

**Comment by omega3** [comment]
But when add-on is disabled it remains white. So I draw conclusion that somehow it affects the look of download window.

**Comment by JustOff** [comment]
What OS and theme are you using?

**Comment by omega3** [comment]
Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.3
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2
Kernel Version: 5.0.5-1-MANJARO
OS Type: 64-bit

Sorry I was wrong. 
With add-on enabled it looks like this
https://i.imgur.com/6C78oGG.png
and download window remains white
https://i.imgur.com/SoUV4Qa.png

Previously I had installed a theme from 
http://addons.palemoon.org/themes/

but I would prefer to be able have ability to customize it with add-on, regardless of theme settings, because themes sometimes are badly designed. Anyway when add-on is enabled shouldn't download window look like normal site, with value set in "Default background color"? At the moment it doesn't, at least for me.

**Comment by JustOff** [comment]
Sorry but there is no.

See also https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/73#issuecomment-297147737.
