### ISSUE TITLE
Page's images vanishes when this extension is active

### ISSUE THREAD

**Issue by resolritter** [JustOff/advanced-night-mode#13]
# Reproduction steps

Go to https://www.subway.com/pt-BR/MenuNutrition/Menu/promocoes

# Description

When this extension is enabled, the deals' images simply do not appear.

Disabling the styles for that specific page **does not work**. You have to literally disable the extension and restart the browser to correctly see the image.

**Comment by JustOff** [comment]
This website contains an iframe served from a different domain - https://www.subwaycms.com.br/171114_promos/index.html, all you need is to open it in a new tab and disable style processing for it.

![image](https://user-images.githubusercontent.com/340855/70847773-10c97f80-1e71-11ea-9a1d-fccb9dc131ba.png)
