### ISSUE TITLE
Request changing the default color scheme

### ISSUE THREAD

**Issue by Fohsap** [JustOff/advanced-night-mode#15]
Being that I help old folks and low-vision users by installing software like this to make reading a little easier on their eyes, I can say that many users are not "advanced users".  The default color scheme is a 'black' color scheme.  Due to an issue with browser standards (SGML or something like that--not-sure forgot), many fields are black by default--this behavior is difficult to correct, and it might be years or decades before we see any changes.  The real solution is for browser to require that all text field have borders (or something like that).  

**Bug!**
Text fields (like search bars and logins) will be **invisible** to users with **black** themes.

**Fix:**
Use a "dark theme", instead.  I highly recommend a dark, olive color.  It's more towards yellow (away from blue), and it's got just enough green that it doesn't cause colorblind users to be blind to text boxes.  But you could also go with dark gray and ignore colorblind users by default.

I'll try to patch it at some point if I can and nobody beats me to it.  Thanks for reading.

**Comment by JustOff** [comment]
Thanks for your feedback, but I tend to leave the default color scheme as it is.
