### ISSUE TITLE
Incompatibility with youtube

### ISSUE THREAD

**Issue by gh-legacy** [JustOff/advanced-night-mode#16]
Currently with the default mode, the background changed to white and all of the comments become invisible. When changed to simple css, the text in search box becomes invisible. The only mode worked is Invert, but this caused terrible performance degrade on youtube. I noticed the extension also attempted to apply the invert into the video's content and the thumbnails of videos where it shouldn't doing so. I'm not sure about this but performance degrade is easily noticeable. Disable the extension on youtube solved the performance degrade problem. Please update this extension to work with youtube, thanks.

**Comment by JustOff** [comment]
At the moment, Pale Moon is barely compatible with the modern version of YouTube.
I will return to this task only when/if it changes.

**Comment by gh-legacy** [comment]
> At the moment, Pale Moon is barely compatible with the modern version of YouTube.
> I will return to this task only when/if it changes.

Don't know about this. But I could watch youtube with 4k quality just fine. I know youtube has a dark theme but it seemed I need to sign in. On Firefox and Chrome it seemed they have an extension that allow activate dark mode without sign in but I have never tried since Dark Reader already worked fine with youtube.

**Comment by JustOff** [comment]
Resolved by https://forum.palemoon.org/viewtopic.php?p=193358#p193358.
