### ISSUE TITLE
Specify preferences for PDFs opened in-browser

### ISSUE THREAD

**Issue by Hal47** [JustOff/advanced-night-mode#17]
Would this be possible to define a specific setting for PDFs on Advanced Night Mode? Ideally, it would both apply to online or local files opened in-browser. 

Currently, the closest I can manage is just disabling the addon for all "file://"

**Comment by JustOff** [comment]
Try [advanced-night-mode-1.0.10b9.xpi](https://github.com/JustOff/advanced-night-mode/releases/download/1.0.9/advanced-night-mode-1.0.10b9.xpi) and use `Default method of changing PDF Viewer colors` in Preferences.

**Comment by JustOff** [comment]
@Hal47 
Did this solve your issue?

**Comment by Hal47** [comment]
@JustOff Sorry for the late reply, I don't know how I missed this but yeah, it solved the issue. Tested it on Pale Moon 28.13.0 and Basilisk 2020.09.11

**Comment by JustOff** [comment]
Thanks, I will include this in the next release.

**Comment by Hal47** [comment]
Solved by 1e1e29356b501626c2eab36506ffaacbdc52d2e4
