### ISSUE TITLE
No Prefs in Linux

### ISSUE THREAD

**Issue by sailsfast** [JustOff/advanced-night-mode#18]
When I try to open the preferences I get an error...  Ubuntu Linux 20.04  Palemoon 28.13.0
"Error. you should not see this"  Same result with ,9 and 1.0.10b9
And, can't read the buttons on the Add ons manager...  Hence why I am trying to access preferences

**Comment by JustOff** [comment]
Can you reproduce this issue using a clean profile with only ANM installed?

**Comment by sailsfast** [comment]
Haven't tried... Don't have a clean profile to work with.
I'll see what I can do.
