### ISSUE TITLE
for Chromium?

### ISSUE THREAD

**Issue by jazei-AR** [JustOff/advanced-night-mode#19]
I`d like this fantastic and RAM Savings add-on for Chromium... Is it possible?

**Comment by JustOff** [comment]
Use the original [Dark Background and Light Text](https://chrome.google.com/webstore/detail/dark-background-and-light/cdcoopnlkdlmphjpjggdmhohkiklonkh).

**Comment by jazei-AR** [comment]
Thank you for your help!!! downloaded! I don`t want to abuse your help.... using (using little by testing only) sea monkey browser an old FF like mypal: is it possible using your add-on? I tried but I could not install lasts versions.... may be an old old version...... anyway whit Chromium and maypal is enough for me!!!
regards!!!!!!!

**Comment by JustOff** [comment]
[Dark Background and Light Text (SeaMonkey)](https://addons.thunderbird.net/en-US/seamonkey/addon/dark-bg-light-text-seamonkey/).

**Comment by jazei-AR** [comment]
Thank you again Guru!!!!
Regards.
