### ISSUE TITLE
Waterfox Classic compatibility

### ISSUE THREAD

**Issue by apapapapapapap** [JustOff/advanced-night-mode#22]
Hi,

i'm trying to install advanced night mode on waterfox classic, but fail.

It works works in principle. When i just move my whole profile-folder from palemoon to waterfox classic it's working for a while perfectly (some mins.?) but then i get a message that it's been disabled because of incompatibility issues.

Any help would be appreciated, tried other similar add-ons for waterfox classic but they're far from the quality of advanced night mode.

Greetings

**Comment by Feodor2** [comment]
Dont use waterfox but maybe can help, did it happen for you to modify a file inside extension?

**Comment by apapapapapapap** [comment]
Hi,

> Dont use waterfox but maybe can help, did it happen for you to modify a
> file inside extension?

I don't modified anything.

Greetings

**Comment by Feodor2** [comment]
You may do modify. What other addons do you use which works?

**Comment by JustOff** [comment]
Sorry, but this will be wontfix for the same reason as described [here](https://github.com/JustOff/advanced-night-mode/issues/14#issuecomment-580703054).
