### ISSUE TITLE
msfn.org things set white on white

### ISSUE THREAD

**Issue by Feodor2** [JustOff/advanced-night-mode#23]
Hi, this is it, here and here. 
https://msfn.org/board/forum/67-windows-vista/
https://msfn.org/board/topic/182647-my-browser-builds-part-3/page/11/?tab=comments#comment-1199693

i have updated to the latest version recently.

**Comment by JustOff** [comment]
This site is incompatible with the stylesheet processor mode, try invert or simple css. You may also want to check whether the site provides a native dark theme.
