### ISSUE TITLE
Basilisk Compatibility

### ISSUE THREAD

**Issue by mixHup** [JustOff/advanced-night-mode#5]
Hi JustOff!

I was just curious if there were any plans to make your Advanced Night Mode addon compatible with the latest Basilisk browser.

Thank you for your time and attention,
mixHup

**Comment by JustOff** [comment]
Sorry, but I'm very unlikely to support Basilisk. You can try to install Advanced Night Mode or the original [Dark Background and Light Text for SeaMonkey](https://addons.thunderbird.net/en-US/seamonkey/addon/dark-bg-light-text-seamonkey/) using [Serpent Tester Tool](https://github.com/Nebula-Mechanica/serpent-tester-tool), but you will be on your own, if something goes wrong.
