### ISSUE TITLE
seamonkey

### ISSUE THREAD

**Issue by apapapapapapap** [JustOff/advanced-night-mode#8]
Can i make this work on seamonkey? i managed to install it, but no symbol and not working. The 'dark background and light text' addon (wich seems to be similar than this) is working in seamonkey. Thanx.

**Comment by JustOff** [comment]
No, you have to use [Dark Background and Light Text (SeaMonkey)](https://addons.thunderbird.net/en-US/seamonkey/addon/dark-bg-light-text-seamonkey/).

**Comment by apapapapapapap** [comment]
Problem is, that i can't control the color-change on per-site basis.

That's only possible in advnced night mode, not in 'dark background and
light text'. Or do you know about a possibility to change the colors on
a per-site-basis in 'dark background and light text'?

Thanx for your help.

**Comment by JustOff** [comment]
> Problem is, that i can't control the color-change on per-site basis.

It works just fine for me on SeaMonkey 2.49.5 + Dark Background and Light Text (SeaMonkey) 0.5.16.

> do you know about a possibility to change the colors on a per-site-basis in 'dark background and light text'? 

You better [ask the original developer](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues).

**Comment by apapapapapapap** [comment]
>     Problem is, that i can't control the color-change on per-site basis.
>
> It works just fine for me on SeaMonkey 2.49.5 + Dark Background and
> Light Text (SeaMonkey) 0.5.16.

Sorry to bother you even if this is not your extension, but how do you
do that? I have the same versions (seamonkey & Dark Background and
Light Text) and there's no option for that.

**Comment by apapapapapapap** [comment]
Forget about my last question. I found out that the
'dark background and light text' extension had a
malfunction here.
